// template/React/code/components/about-section/about-us1/about-us/index.js
import React from 'react';

import { SectionRightImage, CheckboxList, CardStyle4 } from '../../../xamin';

class Index extends React.Component {
    constructor(props) {
        super(props);
       this.state ={
           items:[
               'Advance Advisory Team',
               'Professional Consulting Services',
               '24/7 Support Help Center',
               'Customer Service &amp; Operations'
           ],
           cards :[
               {
                   title:"Data for all people",
                   description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout."
               },
               {
                   title:"A new breed of AI",
                   description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout."
               },
               {
                   title:"Analytics business",
                   description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout."
               },
           ]
       }
    }

    render() {
        const {items,cards } = this.state;

        return (
            <>
                <SectionRightImage
                    title={"About Us"}
                    subTitle={"Human Behaviour, Data Science"}
                    description={"It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout."}
                    image={"./static/assets/images/about-us/06.png"}
                >
                    <CheckboxList
                        text={"text-left"}
                        items={items} />
                </SectionRightImage>
                <section  className="pt-0">
                    <div className="container">
                        <div className="row">
                            { cards.map((item,index) => (
                                <div key={index} className="col-lg-4 col-sm-12">
                                    <CardStyle4
                                        textClass="left"
                                        title={item.title}
                                        description={item.description}
                                    />
                                </div>
                            )) }
                        </div>
                    </div>
                </section>
            </>
        );
    }
}

export default Index;

// template/vue/code/components/AboutUs-1/AboutUs.vue
<template>
  <div>
    <section>
      <div class="container">
        <div class="row iq-how-it-works">
          <div class="iq-mb-30 fadeInUp col-sm-12 col-lg-6 col-md-6 wow align-items-center">
            <div class="title-box wow fadeInUp text-left">
              <span class="title-design">About us</span>
              <h2>Human Behaviour, Data Science</h2>
              <p>It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout.</p>
            </div>
            <div class="text-left">
              <ul class="iq-list">
                  <li> <i class="fas fa-check-square"></i> <span>Advance Advisory Team</span> </li>
                  <li> <i class="fas fa-check-square"></i> <span>Professional Consulting Services</span> </li>
                  <li> <i class="fas fa-check-square"></i> <span> 24/7 Support Help Center</span> </li>
                  <li> <i class="fas fa-check-square"></i> <span>Customer Service &amp; Operations</span> </li>
              </ul>
            </div>
          </div>
          <div class="fadeInUp col-sm-12 col-lg-6 col-md-6 wow"> <img alt="aboutus" class="single_image-img attachment-full" height="954"  :src="require('../../assets/images/about-us/06.png')" width="1260"> </div>
        </div>
      </div>
    </section>
    <section class="pt-0">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 col-sm-12" v-for="(item, index) in list" :key="index">
            <div class="xamin-services  mb-0 wow fadeInUp text-left">
              <div class="services-detail">
                <h4 class="mb-1">{{ item.title }}</h4>
                <p class="mb-0">{{ item.description }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>
<script>
export default {
  name:'AboutUs',
  data(){
    return {
      list:[
        {
          title:'Data for all people',
          description:'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.'
        },
        {
          title:'A new breed of AI',
          description:'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.'
        },
        {
          title:'Analytics business',
          description:'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.'
        }
      ]
    }
  }  
}
</script>
