// template/vue/code/components/LandingPage1/About.vue
<template>
  <div>
    <SectionStyle1>
      <span slot="sectionTitle" class="title-design">About us</span>
      <h2 slot="sectionHeading">
        Focused on Actionable Insights
      </h2>
      <template slot="sectionDescription">
        It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout.
      </template>
      <ul slot="sectionContent" class="iq-list">
        <li v-for="(item,index) of list" :key="index"><i :class="item.icon"> </i><span>{{ item.title }}</span></li>
      </ul>
      <a slot="sectionButton" class="button button-icon" href="#"><span class="btn-effect"> Read More</span> </a>
    </SectionStyle1>
  </div>
</template>

<script>
import SectionStyle1 from '../themes/Sections/SectionStyle1'
export default {
  components: {
    SectionStyle1
  },
  data () {
    return {
      list: [
        {
          icon: 'fas fa-check-square',
          title: 'Advance Advisory Team'
        },
        {
          icon: 'fas fa-check-square',
          title: 'Professional Consulting Services'
        },
        {
          icon: 'fas fa-check-square',
          title: '24/7 Support Help Center'
        },
        {
          icon: 'fas fa-check-square',
          title: 'Customer Service & Operations'
        }
      ]
    }
  }
}
</script>

// template/React/code/components/home-section/landing-page1/about/index.js
import React from 'react';
import Link from "next/link";

import { SectionStyle1, SectionTitle, CheckboxList} from '../../../xamin';

class Index extends React.Component {
    constructor(props) {
        super(props);
        this.state= {
            checklist: [
                "Advance Advisory Team",
                "Professional Consulting Services",
                "24/7 Support Help Center",
                "Customer Service &amp; Operations",
            ]
        };
    }

    render() {
     
        return (
            <>
                <SectionStyle1 rowReverse={true}>
                    <img className="about-box-img" src="./static/assets/images/about-us/02.png"  alt="drive01" />
                    <div className="col-lg-6">
                    </div>
                    <div className="col-lg-6 wow fadeInUp align-items-center">
                        <div  className="title-box wow fadeInUp text-left">
                                <SectionTitle
                                    link ="About us"
                                    title="Focused on Actionable Insights"
                                    subTitle="It is a long established fact that a reader will be distracted by the of readable content of a page when looking at its layout."
                                    className = "title-box wow fadeInUp text-left"
                                    spanclass="title-design"
                                    />
                        </div>
                        
                        <CheckboxList text={"text-left"} items={this.state.checklist} />

                        <div className=" text-left mt-5 ">
                            <Link href="/about-us-1">
                                <a className="button button-icon" > <span className="btn-effect"> Read More</span> </a>
                            </Link>
                        </div>
                    </div>
                </SectionStyle1>     
            </>
        );
    }
}

export default Index;
