// template/React/code/components/home-section/landing-page9/about/index.js
import React from 'react';

import {  SectionTitle, AdressSection} from '../../../xamin';

class   Index extends React.Component {
    constructor(props) {
        super(props);
        this.state={
           
            checkList:[
                {
                    icon:"fa fa-home mr-2",
                    heading:"Location",
                    text:"1234 North Avenue Luke Lane, South Bend, IN 360001",
                    class:"list-inline"
                },
                {
                    icon:"fa fa-phone mr-2",
                    heading:"Phone",
                    text:"+0123456789",
                    class:"list-inline",
                },
                {
                    icon:"fa fa-envelope mr-2",
                    heading:"Email",
                    text:"support@iqnonicthemes.com",
                    class:"list-inline"
                },
                {
                    icon:"fa fa-address-book-o",
                    heading:"Age",
                    text:" 31 Years",
                    class:"list-inline"
                },

              
            ],
        }
    }

    render() {
        const list = this.state.checkList;
        return (
            <>
              <section>
                  <div className="container">
                      <div className="row">
                          <div className="col-lg-5 col-md-5 col-sm-12">
                              <img width="537" height="750" src="./static/assets/images/about-us/19.png" class="attachment-full" alt="about-us"  sizes="100vw" />
                          </div>
                          <div className="col-lg-7 col-md-7 col-sm-12">
                                <SectionTitle
                                    className={"title-box wow fadeInUp text-left"}
                                    spanclass={"title-design"}
                                    link={"ABOUT ME"}
                                    title={"I'm Professional Data Scientist having 10 Years Of Experience"}
                                    subTitle={"Consectetur fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters"}
                                />
                                <ul>
                                    
                                { list.map((item, index) => (
                                    <AdressSection 
                                    icon ={item.icon}
                                    heading ={item.heading}
                                    text ={ item.text}
                                    class={item.class}
                                    />

                                 )) }
                                </ul>
                                <div class=" text-left  "><a class="button blue-btn button-icon" href="#"><span class="btn-effect"> Download CV</span></a></div>
                          </div>
                      </div>

                  </div>
              </section>
            </>
        );
    }
}

export default Index;

// template/vue/code/components/LandingPage9/About.vue
<template>
	<section>
		<div class="container">
			<div class="row">
				<div class="col-lg-5 col-md-5 col-sm-12">
					<img width="537" height="750" :src="require('../../assets/images/about-us/19.png')" class="attachment-full" alt="about-us"  sizes="100vw">
				</div>
				<div class="col-lg-7 col-md-7 col-sm-12">
					<div class="title-box wow fadeInUp ">
						<span class="title-design">ABOUT ME</span>
						<h2>I'm Professional Data Scientist having 10 Years Of Experience</h2>
						<p>Consectetur fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.</p>
					</div>
					<ul class="iq-address">
						<li><a><i class="fa fa-home mr-2"></i><span class="header">Location</span><span class="content">: 1234 North Avenue Luke Lane, South Bend, IN 360001</span></a></li>
						<li class="list-inline"><a href="tel:+0123456789"><i class="fas fa-phone-alt mr-2"></i><span class="header">Phone</span><span class="content"> : +0123456789</span></a></li>
						<li class="list-inline"><a href="mailto:support@iqnonicthemes.com"><i class="fas fa-envelope mr-2"></i><span class="header">Email</span><span class="content"> : support@iqnonicthemes.com</span></a></li>
						<li ><a><i class="fas fa-address-book mr-2"></i><span class="header">Age</span><span class="content"> : 31 Years</span></a></li>
					</ul>
					<div class="text-left"><a class="button blue-btn button-icon" href="#"><span class="btn-effect"> Download CV</span></a></div>
				</div>
			</div>
		</div>
	</section>
</template>
<script>
export default {
	name: 'About'
}
</script>
